version: '3.3'

services:
  django:
    build: ./bookie
    command: gunicorn bookie.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./db/:/usr/src/app/db
      - static_volume:/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 8012:80
    depends_on:
      - django

volumes:
  static_volume: