version: '3.3'

services:
  web:
    build: ./bookie
    command: gunicorn bookie.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./bookie/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env