# Generated by Django 4.2.1 on 2023-06-05 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('earnings_per_flight', models.FloatField(default=0)),
                ('earnings_bonus', models.FloatField(default=0)),
                ('earnings_photos_desk', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmen',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.FloatField(default=0)),
                ('distance', models.FloatField(default=0)),
                ('tandemflight', models.BooleanField(default=False)),
                ('vkpi', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Flug',
                'verbose_name_plural': 'Flüge',
            },
        ),
        migrations.CreateModel(
            name='FlightBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilot', models.CharField(max_length=64)),
                ('number_of_flights', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Flugbuch',
                'verbose_name_plural': 'Flugbücher',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('height', models.FloatField(default=None)),
            ],
            options={
                'verbose_name': 'Fluggebiet',
                'verbose_name_plural': 'Fluggebiete',
            },
        ),
        migrations.CreateModel(
            name='Wing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=64)),
                ('brand', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('size', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=64)),
                ('number_of_flights', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Schirm',
                'verbose_name_plural': 'Schirme',
            },
        ),
        migrations.CreateModel(
            name='CommercialFlight',
            fields=[
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='flightbook.flight')),
                ('company', models.CharField(max_length=64)),
                ('double_airtime', models.BooleanField(default=False)),
                ('trip_time', models.CharField(max_length=64)),
                ('photos_sold', models.BooleanField(default=False)),
                ('cash_payment', models.BooleanField(default=False)),
                ('desk_payment', models.BooleanField(default=False)),
                ('credit_card_payment', models.BooleanField(default=False)),
                ('tip', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Kommerzieller Flug',
                'verbose_name_plural': 'Kommerzielle Flüge',
            },
        ),
        migrations.AddField(
            model_name='flight',
            name='flightbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightbook.flightbook'),
        ),
        migrations.AddField(
            model_name='flight',
            name='landing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing', to='flightbook.site'),
        ),
        migrations.AddField(
            model_name='flight',
            name='takeoff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeoff', to='flightbook.site'),
        ),
        migrations.AddField(
            model_name='flight',
            name='wing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightbook.wing'),
        ),
    ]
