# Generated by Django 4.2.1 on 2023-08-06 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flightbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercialflight',
            old_name='tip',
            new_name='tip_cash',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='earnings_bonus',
            new_name='earnings_da_bonus',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='height',
            new_name='altitude',
        ),
        migrations.RenameField(
            model_name='wing',
            old_name='brand',
            new_name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='vkpi',
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='tip_credit_card',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='commercialflight',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightbook.company'),
        ),
        migrations.AlterField(
            model_name='flightbook',
            name='pilot',
            field=models.CharField(max_length=64, verbose_name='Pilot:In'),
        ),
    ]
