# Generated by Django 4.2.1 on 2023-08-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightbook', '0002_rename_tip_commercialflight_tip_cash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialflight',
            name='cash_payment',
        ),
        migrations.RemoveField(
            model_name='commercialflight',
            name='credit_card_payment',
        ),
        migrations.RemoveField(
            model_name='commercialflight',
            name='desk_payment',
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='photo_payment',
            field=models.CharField(choices=[('Bar', 'Bar'), ('Desk', 'Desk'), ('Kreditkarte', 'Kreditkarte')], default='Kreditkarte', max_length=16),
        ),
        migrations.AlterField(
            model_name='flight',
            name='distance',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.FloatField(default=None),
        ),
    ]
