# Generated by Django 4.2.1 on 2023-08-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightbook', '0003_remove_commercialflight_cash_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercialflight',
            old_name='tip_cash',
            new_name='tip',
        ),
        migrations.RemoveField(
            model_name='commercialflight',
            name='tip_credit_card',
        ),
        migrations.AddField(
            model_name='commercialflight',
            name='tip_payment',
            field=models.CharField(choices=[('Bar', 'Bar'), ('Kreditkarte', 'Kreditkarte')], default='Bar', max_length=16),
        ),
    ]
