# Generated by Django 4.2.1 on 2023-08-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightbook', '0004_rename_tip_cash_commercialflight_tip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialflight',
            name='trip_time',
            field=models.CharField(choices=[('07:15', '07:15'), ('08:15', '08:15'), ('09:30', '09:30'), ('10:40', '10:40'), ('11:50', '11:50'), ('13:00', '13:00'), ('14:15', '14:15'), ('15:30', '15:30'), ('16:45', '16:45'), ('18:00', '18:00')], max_length=16),
        ),
    ]
