# Generated by Django 4.2.1 on 2023-08-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightbook', '0005_alter_commercialflight_trip_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialflight',
            name='tip',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='distance',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.FloatField(default=None, null=True),
        ),
    ]
