# Generated by Django 4.2.1 on 2023-08-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightbook', '0006_alter_commercialflight_tip_alter_flight_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='distance',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
