# Generated by Django 4.2.1 on 2023-08-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightbook', '0008_alter_commercialflight_photo_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialflight',
            name='photo_payment',
            field=models.CharField(blank=True, choices=[(None, 'Keine Fotos'), ('Bar', 'Bar'), ('Desk', 'Desk'), ('Kreditkarte', 'Kreditkarte')], default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='commercialflight',
            name='tip_payment',
            field=models.CharField(blank=True, choices=[(None, 'Kein Trinkgeld'), ('Bar', 'Bar'), ('Kreditkarte', 'Kreditkarte')], default=None, max_length=16, null=True),
        ),
    ]
