# Generated by Django 4.2.1 on 2023-08-06 20:25

from django.db import migrations, models

def fill_taskid(apps, schema_editor):
    # be sure to change it to your app here
    CommercialFlight = apps.get_model("flightbook", "CommercialFlight")
    db_alias = schema_editor.connection.alias
    flights = CommercialFlight.objects.using(db_alias).all()
    for i, flight in enumerate(flights):
        flight.id = i
    CommercialFlight.objects.using(db_alias).bulk_update(flights, ["id"])


class Migration(migrations.Migration):

    dependencies = [
        ('flightbook', '0009_alter_commercialflight_photo_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialflight',
            name='id',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(fill_taskid),
        migrations.AlterField(
            model_name='commercialflight',
            name='id',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
