# Generated by Django 4.2.1 on 2023-08-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightbook', '0010_auto_20230806_2225'),
    ]

    operations = [
    ]
