# Generated by Django 4.2.1 on 2023-08-07 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flightbook', '0011_auto_20230806_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialflight',
            name='flight',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flightbook.flight'),
        ),
        migrations.AlterField(
            model_name='commercialflight',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
